---

name: CI
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'deekayen.dotnet452'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'deekayen.dotnet452'

      - name: Install test dependencies.
        run: pip3 install ansible-lint

      - name: Lint ansible.
        run: ansible-lint
